Feature/guest
basecom/Pond pull request #32
Opened 2024-09-04 09:37 UTC by mloeffle

2024-09-06 12:29 UTC, jkniest requested changes

2024-09-06 12:29 UTC, jkniest commented on components/account/AccountRegister.vue
> +    console.log(fields.target.checked);
```suggestion
```

2024-09-06 12:29 UTC, jkniest commented on pages/search/index.vue
> +                results for "<strong>{{ searchTerm }}</strong
Dont know what happend here but please revert

2024-09-06 14:29 UTC, mloeffle commented on pages/search/index.vue
> +                results for "<strong>{{ searchTerm }}</strong
the linting is responsible for this actually. something seems to get confused by the tag between double quotes

2024-09-09 13:58 UTC, aheartforspinach commented on components/Utility/UtilityPill.vue
> +        class="h-3.5 min-w-3.5 rounded-full bg-brand-primary p-0.5 text-xs leading-none text-white outline outline-1 outline-white"
why did we remove `grid items-center justify-center`?

2024-09-09 13:58 UTC, aheartforspinach commented on components/account/AccountRegister.vue
> +        pushSuccess('You successfully logged in as a guest.');
I'm confused, sorry :D Why are we logged in as a guest?

2024-09-09 15:53 UTC, mloeffle commented on components/Utility/UtilityPill.vue
> +        class="h-3.5 min-w-3.5 rounded-full bg-brand-primary p-0.5 text-xs leading-none text-white outline outline-1 outline-white"
just checked again and added flex instead. but the reason in general was, that `grid` didn't have any impact on how the pill wad styled. which positions the content vertically more centered while grid did not as far as i could see on my devices

2024-09-09 15:55 UTC, mloeffle commented on components/account/AccountRegister.vue
> +        pushSuccess('You successfully logged in as a guest.');
:D wasn't sure about this too but wanted to keep the consistency and have some kind of feedback, but maybe its better to remove this and let the change of the form be enough

2024-09-18 15:10 UTC, m-borgmann commented on components/Account/AccountRegister.vue
> +            label="dont create a customer account"
Translation

2024-09-18 15:10 UTC, m-borgmann commented on components/Account/AccountRegister.vue
> +        pushSuccess('You successfully logged in');
Translations hier und in 47

2024-09-18 15:12 UTC, m-borgmann approved these changes

2024-09-20 08:07 UTC, mloeffle commented
On Hold until config route is implemented to toggle the functionality.

2024-11-07 10:18 UTC, m-borgmann commented on i18n/de-DE/account.json
> +            },
Brauchen wir hierfür keine englischen Translations?

2024-11-11 14:54 UTC, aheartforspinach approved these changes

2024-11-11 15:21 UTC, merged