Feature/TQLG 100 wishlist functionality
basecom/Pond pull request #43
Opened 2024-09-18 00:51 UTC by paulapopDD

The user can add a product to wishlist, remove a product from wishlist, see the wishlist on the wishlist page.

2024-09-20 07:22 UTC, mloeffle commented on components/Shared/SharedAddToWishlist.vue
> +</template>
could you move the template tag underneath the script tag so it is consistent?

2024-09-20 07:23 UTC, mloeffle commented on components/Shared/SharedAddToWishlist.vue
> +<template>
Could you rename the componenten to `ProductAddToWishlist` and move it to the product folder?
this component will only be useful for products and wont be used for different situation so it can be grouped into there

2024-09-20 07:55 UTC, mloeffle commented on pages/wishlist.vue
> +    const { data } = await apiClient.invoke("readProduct post /product", {
could you try using [useAsyncData](https://nuxt.com/docs/api/composables/use-async-data)?
It does offer some benefits compared to fetching directly. Eg it has an build in watch method and gives the reactive variable `status` which saves us handling the isLoading status ourself, also it allows to cache requests so they wont be fired every time.

2024-09-20 07:59 UTC, mloeffle commented on pages/wishlist.vue
> +onMounted(async () => {
Could you test if the `onMounted` is needed?
We should try to avoid using the onMounted if not neccessary because we lose the benefits of server side rendering

2024-09-20 07:59 UTC, mloeffle commented on pages/wishlist.vue
> +  <div class="relative container mx-auto" >
```suggestion
    <div class="relative container mx-auto" >
```

2024-09-20 08:06 UTC, mloeffle commented on pages/wishlist.vue
> +  </div>
```suggestion
    </div>  
```

2024-09-23 07:35 UTC, mloeffle commented on components/Cms/Element/CmsElementBuyBox.vue
> +       </div>
indentation seems a bit off here, could you run `bun run lint`

2024-09-23 07:36 UTC, mloeffle commented on components/Product/ProductAddToWishlist.vue
> +    else{
```suggestion
    } else {
```

2024-09-23 07:47 UTC, mloeffle commented on components/Product/ProductCard.vue
> +import ProductAddToWishlist from './ProductAddToWishlist.vue';
```suggestion
```

should not be necessary due to autoimporting

2024-09-23 12:13 UTC, m-borgmann requested changes
I checked out your branch and found an issue. Steps to reproduce:

1. Go to a listing page and add a product to the wishlist
2. Go to the detail page of that product
3. The heart next to the buy button should be filled out, since the product has already been added to the wishlist
4. The heart is not filled out however. This allows the user to add the product a second time to the wishlist
5. Adding the product a second time leads to a rendering problem on the wishlist page. Instead of displaying the product, it says that the wishlist is empty.

The issue seems to be that adding a product to the wishlist from the pdp does not correctly add the ID of the product to the wishlist. Inspecting the localStorage reveals this:
`["product.id"]` instead of the actual ID string

In fact, it seems to be that adding a product from the pdp in general does not seem to work.

Please fix the described issue. If a product is already on the wishlist, it should be filled out on the product detail page. Clicking it should remove it. This should also fix the display on the wishlist page, since it should no longer be possible for a user to add the same product twice.

2024-09-23 12:16 UTC, m-borgmann commented on components/Product/ProductAddToWishlist.vue
> +
```suggestion
```

2024-09-23 12:17 UTC, m-borgmann commented on components/Product/ProductAddToWishlist.vue
> +            pushInfo( t('wishlist.removedSuccesfully'))
```suggestion
            pushInfo(t('wishlist.removedSuccesfully'))
```

2024-09-23 12:17 UTC, m-borgmann commented on components/Product/ProductAddToWishlist.vue
> +            pushSuccess( t('wishlist.addedSuccesfully'))
```suggestion
            pushSuccess(t('wishlist.addedSuccesfully'))
```

2024-09-23 12:17 UTC, m-borgmann commented on components/Product/ProductAddToWishlist.vue
> +<template>
```suggestion
</script>

<template>
```

2024-09-26 12:13 UTC, m-borgmann approved these changes

2024-09-26 14:41 UTC, merged