Feature/tqlg 138 cookie consent
basecom/Pond pull request #51
Opened 2024-09-23 21:26 UTC by adnansaadeddine

2024-09-26 09:36 UTC, aheartforspinach commented on composables/useCookieGroupsHelper.ts
> +export const useCookieGroupsHelper = () => {
Could we extract everything from line 15 until end of file in a composable? I think its more suiteable there

2024-09-26 09:36 UTC, aheartforspinach commented on composables/useCookieGroupsHelper.ts
> +            name: 'Technically required',
We should use i18n for all snippets or why is it in english?

2024-09-26 11:07 UTC, adnansaadeddine commented on composables/useCookieGroupsHelper.ts
> +            name: 'Technically required',
When I created the PR the translation were not part of pond. I will update the code

2024-09-26 11:24 UTC, adnansaadeddine commented on composables/useCookieGroupsHelper.ts
> +            name: 'Technically required',
Actually I updated the code, I just forgot about the translations from here, sorry

2024-09-26 12:40 UTC, aheartforspinach approved these changes

2024-09-26 12:51 UTC, m-borgmann requested changes
I checked out your branch locally and found some Issues:

Issue 1 - Steps to reproduce:
- Visit page for the first time, so the configure banner appears
- Click "Configure"
- In the modal that opens, click "more Information" link in the text
- This closes the current modal, does not open a new one and also sets the cookie preference so the banner no longer appears
- It is possible that customer goes that route and now has no Idea what his cookies are set to
- Clicking on that link from the configure modal should not set the cookie preference to 1

Issue 2 - Steps to reproduce:
- Navigate to a page with content so that you can scroll down the page
- Open the cookie configure from the configure banner or from the footer icon
- This freezes the scrolling for the user, but the modal does not appear in the middle of the screen
- The user cant see all the information
- The configure modal should always be centered so the user can see all the information


Additional Feature Request:
This was not required in the ticket but I think it would be nice to have an option to display a "accept all" and "reject all" button in the configure modal, alongside the "save" button. so the user has some quick options from the configure modal aswell and not just in the banner.

2024-09-27 17:13 UTC, adnansaadeddine commented
I forgot to fix second issue

2024-09-30 11:05 UTC, m-borgmann commented on i18n/de-DE/cookie.json
> +      "allowAllButton": "Akzeptiere alles"
```suggestion
      "submitLabel": "Auswahl speichern",
      "denyAllButton": "Alle ablehnen",
      "allowAllButton": "Alle akzeptieren"
```

2024-09-30 11:06 UTC, m-borgmann commented on i18n/en-GB/cookie.json
> +      "submitLabel": "Save",
```suggestion
      "submitLabel": "Save selection",

```

2024-09-30 11:06 UTC, m-borgmann approved these changes

2024-09-30 12:31 UTC, merged