Feature/improve hydration
basecom/Pond pull request #93
Opened 2024-11-28 14:05 UTC by mloeffle

- reduces hydration mismatches
- refactors cookie modal
- adjust product card display to prevent overflow of form

2024-11-29 10:31 UTC, m-borgmann commented on components/Cms/Block/CmsBlockProductListing.vue
> +        class="-mx-5"
Not a big fan of negative margin personally. Do we really need this?

2024-11-29 10:33 UTC, m-borgmann approved these changes

2024-12-02 12:25 UTC, jkniest requested changes

2025-01-14 14:44 UTC, aheartforspinach commented
@mloeffle do we still need this pull request? should we merge it or close it?

2025-02-21 07:15 UTC, aheartforspinach commented
✅ merge request closed

will be part of the refactoring

2025-02-21 07:15 UTC, closed without merging